"""
PARAMETROS CASINO
"""

DEUDA_TOTAL = 2_000
PROBABILIDAD_EVENTO = None

"""
PARAMETROS BEBESTIBLES
"""

MIN_ENERGIA_BEBESTIBLE = 3
MAX_ENERGIA_BEBESTIBLE = 10


"""
PARAMETROS JUGADORES
"""

# Todo lo afectado por el multiplicador se redondea si es un int
MULTIPLICADOR_BONIFICACION_BEBEDOR = 1.5

BONIFICACION_SUERTE_CASUAL = None

PORCENTAJE_APUESTA_TACANO = 0.05
BONIFICACION_TACANO = 100

"""
PARAMETROS JUEGOS
"""

FRUSTRACION_PERDER = None
CONFIANZA_PERDER = None

EGO_GANAR = None
CARISMA_GANAR = None
FRUSTRACION_GANAR = None
